#!/bin/bash

echo "Modificamos as pantallas de carga e de saí­da/apagado"

# Descargamos o logotipo da USC
wget http://minino.galpon.org/public/USC/logo-usc.jpg -O /usr/local/share/icons/USC/logo-usc.jpg

# Descargamos os logotipos especiais de «plymouth para o tema «joy-minino»
wget http://minino.galpon.org/public/USC/usc_logo.png -O /usr/share/plymouth/themes/joy-minino/usc_logo.png
wget http://minino.galpon.org/public/USC/usc_logo16.png -O /usr/share/plymouth/themes/joy-minino/usc_logo16.png
wget http://minino.galpon.org/public/USC/progress_dot_on.png -O /usr/share/plymouth/themes/joy-minino/progress_dot_on.png
wget http://minino.galpon.org/public/USC/progress_dot_on16.png -O /usr/share/plymouth/themes/joy-minino/progress_dot_on16.png

# Modificar as definicións en /usr/share/plymouth/themes/joy-minino/joy-minino.script
sed -i -r -e 's/minino/usc/g' /usr/share/plymouth/themes/joy-minino/joy-minino.script

# Pisar o ficheiro de configuración do texto e imaxe da xanela de apagado
cat <<EOF > /usr/local/bin/lxde-logout
#!/bin/sh
TXT="<span size='x-large'><i>Coa tecnoloxía de</i>
<b>MiniNo</b> <i>Ártabros</i></span>"
IMG="/usr/local/share/icons/logo-usc.jpg"
lxsession-logout --prompt "\$TXT" --banner "\$IMG" --side=top
EOF

echo
echo "Modificadas as pantallas carga e de de saí­da/apagado"

echo
echo "Modificamos o fondo de pantalla polo da USC"

# Descargamos o fondo da USC
wget http://minino.galpon.org/public/USC/fondo-usc.png -O /usr/local/share/pixmaps/minino-wallpaper/fondo-usc.png

# Modificamos o ficheiro «pcmanfm.conf»
sed -i -r -e 's/minino-wallpaper-1_1280x1024.jpg/wallpaper-usc/g' /home/$USUARIO/.config/pcmanfm/LXDE/pcmanfm.conf
sed -i -r -e 's/minino-wallpaper-1_1280x1024.jpg/fondo-usc.png/g' /etc/skel/.config/pcmanfm/LXDE/pcmanfm.conf
sed -i -r -e 's/minino-wallpaper-1_1280x1024.jpg/fondo-usc.png/g' /etc/xdg/pcmanfm/LXDE/pcmanfm.conf

echo
echo "Modificado o fondo de pantalla"

